name: '🎛️ Atualizar Versão'
description: 'Atualiza a versão do modulo e realiza um commit.'
inputs:
  version:
    description: 'Nova versão para ser definida no modulo.'
    required: true
  github_token:
    description: 'Token para clonar workspace'
    required: true 
runs:
  using: 'composite'
  steps:
    - name: 'Build Core'
      if: github.repository != 'GEDPaciente/core'
      id: build-core
      uses: GEDPaciente/workflows/build-core@main
      with:
        github_token: ${{ inputs.github_token }}

    - name: 'Finalizado build core'
      if: github.repository != 'GEDPaciente/core'
      run: |
        echo "Core Buildado, iniciando clonagem do modulo"
      shell: bash
      
    - name: 'Checkout Repository'
      uses: actions/checkout@v3
      with:
        path: module
        fetch-depth: 0
        
    - name: 'Set up JDK 17'
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        
    - name: 'Build'
      run: |
        cd module
        git pull
        echo "Buildando modulo"
        mvn clean install -DskipTests -N -q
        echo "Modulo Buildado"
      shell: bash

    - name: Verificar versão
      run: |
        cd module
        CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Versão atual: $CURRENT_VERSION"
        if [ "$CURRENT_VERSION" == "${{ inputs.version }}" ]; then
          echo "Versão atual já é $CURRENT_VERSION. Nenhuma atualização necessária."
          echo "skip_commit=true" >> $GITHUB_ENV
        fi
        
        echo "module_version=$CURRENT_VERSION" >> $GITHUB_ENV
      shell: bash

    - name: 📝 Update Version
      if: env.skip_commit != 'true'
      run: |
        cd module
        echo "Atualizando versão para ${{ inputs.version }}"
        mvn versions:set -DnewVersion="${{ inputs.version }}" -DgenerateBackupPoms=false -q
        
        if [ -f package.json ]; then
          echo "Atualizando versão no package.json para ${{ inputs.version }}"
          jq --arg version "$module_version" '.version = ${{ inputs.version }}' package.json > package.json.tmp
          mv package.json.tmp package.json
        fi
      shell: bash

    - name: Commit
      if: env.skip_commit != 'true'
      run: |
        cd module
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add pom.xml
        
        if [ -f package.json ]; then
          git add package.json
        fi

        VERSION_SEMANTIC=v${{ inputs.version }}
        
        git commit -m "Atualização de Versão - $VERSION_SEMANTIC"
        git push
        echo "Versão atualizada para $module_version"
      shell: bash
