name: '🎛️ Build Modulo'
description: 'Fluxo de atualização do Modulo'
inputs:
  github_token:
    description: 'Token de acesso ao GitHub'
    required: true
outputs:
  module_version:
    description: 'Versão do Modulo'
    value: ${{ steps.get_version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: 🔒 Verificar GitHub Token
      run: |
        if [ -z "${{ inputs.github_token }}" ]; then
          echo "GitHub Token não fornecido."
          exit 1
        else
          echo "GitHub Token está presente."
        fi
      shell: bash

    - name: 'Checkout Repositório Parent'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        repository: GEDPaciente/mv-ged-parent
        token: ${{ inputs.github_token }}
        path: parent

    - name: 'Set up JDK 17'
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
    - name: 'Obter o nome do repositório que disparou a ação'
      run: |
        REPO_NAME=$(basename "${{ github.repository }}")
        echo "O nome do repositório que disparou a action é: $REPO_NAME"
        echo "repo_name=$REPO_NAME" >> $GITHUB_ENV
      shell: bash

    - name: Build do Parent, Cores e Submódulo Específico
      id: build-only-modules
      run: |
        cd parent
        if [[ ! "$GITHUB_REPOSITORY" == "GEDPaciente/mv-ged-core" && ! "$GITHUB_REPOSITORY" == "GEDPaciente/mv-gap-core" ]]; then
          echo "Buildando cores e ${{env.repo_name}}"
          mvn clean package -pl mv-ged-core,mv-gap-core,${{ env.repo_name }} -am -DskipTests -q
        else
            if [[ "$GITHUB_REPOSITORY" == "GEDPaciente/mv-ged-core" ]]; then
              echo "Buildando somente GED-CORE"
              mvn clean package -pl mv-ged-core -DskipTests -q
            elif [[ "$GITHUB_REPOSITORY" == "GEDPaciente/mv-gap-core" ]]; then
              echo "Buildando somente GAP-CORE"
              mvn clean package -pl mv-gap-core -DskipTests -q
            fi
        fi

        echo "Build COMPLETO! ${{ env.repo_name }}"
        
      shell: bash

    - name: 'Copiar Arquivos'
      run: |
        
        mkdir -p core/target
        
        if [[ -d "parent/mv-ged-core/target" ]]; then
          cp parent/mv-ged-core/target/*.jar core/target/
          echo "JAR GED-CORE copiado para core/target"
        fi

        if [[ -d "parent/mv-gap-core/target" ]]; then        
          cp parent/mv-gap-core/target/*.jar core/target/
          echo "JAR GAP-CORE copiado para core/target"
        fi        

        ln -s "parent/${{ env.repo_name }}" module
        echo "Symlink criado para a pasta do repositório em 'module'"

    